### ISSUE TITLE
Could you pick a license and add it to package.json?

### ISSUE THREAD

**Issue by silviapfeiffer** [DamonOehlman/feature#3]
Sorry to be a pain ;-)

**Comment by DamonOehlman** [comment]
No problem - is ISC still ok?  It seems to be the preferred default for npm and so what I'm using most often.

**Comment by silviapfeiffer** [comment]
ISC, MIT, BSD - any of those would be awesome. Must npm packages we use ate actually MIT. They are compatible licences faik, so either works.
